// "use client";
import "./globals.css";
import Header from "@/components/Header/Header";
import { Providers } from "@/redux/providers";
// import { ThemeProvider } from "next-themes";
// import Provviders from "./provviders";
import { ThemeSwitcher } from "./ThemeSwitcher";

export const metadata = {
  title: "GrowwStonks",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/favicon.ico",
    apple: "/assets/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="light" style={{colorScheme: 'light'}}>
      <body className="dark">
        <Providers>
          <Header />
          <ThemeSwitcher />
          {children}
        </Providers>
      </body>
    </html>
  );
}
